services:
  retroarch-sunshine:
    devices:
      - /dev/dri:/dev/dri
      - /dev/uinput:/dev/uinput
    device_cgroup_rules:
      - "c 13:* rwm"
      - "c 10:223 rwm"
    volumes:
      - /dev/input:/dev/input
    group_add:
      - video
      - input
