file_apps = /config/apps.json
log_path = /config/logs/sunshine.log
sunshine_name = RetroArch Sunshine
min_log_level = info
system_tray = disabled
notify_pre_releases = disabled
upnp = disabled
origin_web_ui_allowed = lan
audio_sink = retroarch_sink.monitor
virtual_sink = retroarch_sink
