[supervisord]
nodaemon=true
logfile=/dev/null
pidfile=/tmp/supervisord.pid
user=root

[program:dbus]
command=/usr/local/bin/start-dbus
autorestart=true
priority=1
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0

[program:udev]
command=/usr/local/bin/start-udev
autorestart=true
priority=5
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0

[program:xorg]
command=/usr/local/bin/start-xorg-dummy
autorestart=true
priority=10
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0

[program:pulseaudio]
command=/usr/local/bin/start-pulseaudio
autorestart=true
priority=20
environment=HOME="/tmp/pulse-home",XDG_CONFIG_HOME="/tmp/pulse-home/.config",XDG_RUNTIME_DIR="%(ENV_XDG_RUNTIME_DIR)s"
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0

[program:openbox]
command=/usr/local/bin/start-openbox
autorestart=true
priority=30
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0

[program:sunshine]
command=/usr/local/bin/start-sunshine
autorestart=true
priority=40
environment=DISPLAY="%(ENV_DISPLAY)s",PULSE_SERVER="%(ENV_PULSE_SERVER)s",XDG_RUNTIME_DIR="%(ENV_XDG_RUNTIME_DIR)s",HOME="/config",XDG_CONFIG_HOME="/config/.config"
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0
